[project]
name = "dnn-surgery"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "grpcio>=1.73.0",
    "grpcio-tools>=1.73.0",
]
