# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dnn_inference.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'dnn_inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64nn_inference.proto\x12\x0b\x64nn_surgery\"!\n\x0bTensorShape\x12\x12\n\ndimensions\x18\x01 \x03(\x05\"e\n\x06Tensor\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\'\n\x05shape\x18\x02 \x01(\x0b\x32\x18.dnn_surgery.TensorShape\x12\r\n\x05\x64type\x18\x03 \x01(\t\x12\x15\n\rrequires_grad\x18\x04 \x01(\x08\"I\n\x10InferenceRequest\x12#\n\x06tensor\x18\x01 \x01(\x0b\x32\x13.dnn_surgery.Tensor\x12\x10\n\x08model_id\x18\x02 \x01(\t\"`\n\x11InferenceResponse\x12#\n\x06tensor\x18\x01 \x01(\x0b\x32\x13.dnn_surgery.Tensor\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t2`\n\x0c\x44NNInference\x12P\n\rProcessTensor\x12\x1d.dnn_surgery.InferenceRequest\x1a\x1e.dnn_surgery.InferenceResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dnn_inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENSORSHAPE']._serialized_start=36
  _globals['_TENSORSHAPE']._serialized_end=69
  _globals['_TENSOR']._serialized_start=71
  _globals['_TENSOR']._serialized_end=172
  _globals['_INFERENCEREQUEST']._serialized_start=174
  _globals['_INFERENCEREQUEST']._serialized_end=247
  _globals['_INFERENCERESPONSE']._serialized_start=249
  _globals['_INFERENCERESPONSE']._serialized_end=345
  _globals['_DNNINFERENCE']._serialized_start=347
  _globals['_DNNINFERENCE']._serialized_end=443
# @@protoc_insertion_point(module_scope)
