# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resource_handle.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'resource_handle.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import tensor_shape_pb2 as tensor__shape__pb2
import types_pb2 as types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15resource_handle.proto\x1a\x12tensor_shape.proto\x1a\x0btypes.proto\"\xfe\x01\n\x13ResourceHandleProto\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\t\x12=\n\x11\x64types_and_shapes\x18\x06 \x03(\x0b\x32\".ResourceHandleProto.DtypeAndShape\x1aK\n\rDtypeAndShape\x12\x18\n\x05\x64type\x18\x01 \x01(\x0e\x32\t.DataType\x12 \n\x05shape\x18\x02 \x01(\x0b\x32\x11.TensorShapeProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resource_handle_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESOURCEHANDLEPROTO']._serialized_start=59
  _globals['_RESOURCEHANDLEPROTO']._serialized_end=313
  _globals['_RESOURCEHANDLEPROTO_DTYPEANDSHAPE']._serialized_start=238
  _globals['_RESOURCEHANDLEPROTO_DTYPEANDSHAPE']._serialized_end=313
# @@protoc_insertion_point(module_scope)
