# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tensor.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'tensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import tensor_shape_pb2 as tensor__shape__pb2
import types_pb2 as types__pb2
import resource_handle_pb2 as resource__handle__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctensor.proto\x1a\x12tensor_shape.proto\x1a\x0btypes.proto\x1a\x15resource_handle.proto\"\xe0\x03\n\x0bTensorProto\x12\x18\n\x05\x64type\x18\x01 \x01(\x0e\x32\t.DataType\x12\'\n\x0ctensor_shape\x18\x02 \x01(\x0b\x32\x11.TensorShapeProto\x12\x16\n\x0eversion_number\x18\x03 \x01(\x05\x12\x16\n\x0etensor_content\x18\x04 \x01(\x0c\x12\x14\n\x08half_val\x18\r \x03(\x05\x42\x02\x10\x01\x12\x15\n\tfloat_val\x18\x05 \x03(\x02\x42\x02\x10\x01\x12\x16\n\ndouble_val\x18\x06 \x03(\x01\x42\x02\x10\x01\x12\x13\n\x07int_val\x18\x07 \x03(\x05\x42\x02\x10\x01\x12\x12\n\nstring_val\x18\x08 \x03(\x0c\x12\x18\n\x0cscomplex_val\x18\t \x03(\x02\x42\x02\x10\x01\x12\x15\n\tint64_val\x18\n \x03(\x03\x42\x02\x10\x01\x12\x14\n\x08\x62ool_val\x18\x0b \x03(\x08\x42\x02\x10\x01\x12\x18\n\x0c\x64\x63omplex_val\x18\x0c \x03(\x01\x42\x02\x10\x01\x12\x31\n\x13resource_handle_val\x18\x0e \x03(\x0b\x32\x14.ResourceHandleProto\x12,\n\x0bvariant_val\x18\x0f \x03(\x0b\x32\x17.VariantTensorDataProto\x12\x16\n\nuint32_val\x18\x10 \x03(\rB\x02\x10\x01\x12\x16\n\nuint64_val\x18\x11 \x03(\x04\x42\x02\x10\x01\"\\\n\x16VariantTensorDataProto\x12\x11\n\ttype_name\x18\x01 \x01(\t\x12\x10\n\x08metadata\x18\x02 \x01(\x0c\x12\x1d\n\x07tensors\x18\x03 \x03(\x0b\x32\x0c.TensorProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENSORPROTO'].fields_by_name['half_val']._loaded_options = None
  _globals['_TENSORPROTO'].fields_by_name['half_val']._serialized_options = b'\020\001'
  _globals['_TENSORPROTO'].fields_by_name['float_val']._loaded_options = None
  _globals['_TENSORPROTO'].fields_by_name['float_val']._serialized_options = b'\020\001'
  _globals['_TENSORPROTO'].fields_by_name['double_val']._loaded_options = None
  _globals['_TENSORPROTO'].fields_by_name['double_val']._serialized_options = b'\020\001'
  _globals['_TENSORPROTO'].fields_by_name['int_val']._loaded_options = None
  _globals['_TENSORPROTO'].fields_by_name['int_val']._serialized_options = b'\020\001'
  _globals['_TENSORPROTO'].fields_by_name['scomplex_val']._loaded_options = None
  _globals['_TENSORPROTO'].fields_by_name['scomplex_val']._serialized_options = b'\020\001'
  _globals['_TENSORPROTO'].fields_by_name['int64_val']._loaded_options = None
  _globals['_TENSORPROTO'].fields_by_name['int64_val']._serialized_options = b'\020\001'
  _globals['_TENSORPROTO'].fields_by_name['bool_val']._loaded_options = None
  _globals['_TENSORPROTO'].fields_by_name['bool_val']._serialized_options = b'\020\001'
  _globals['_TENSORPROTO'].fields_by_name['dcomplex_val']._loaded_options = None
  _globals['_TENSORPROTO'].fields_by_name['dcomplex_val']._serialized_options = b'\020\001'
  _globals['_TENSORPROTO'].fields_by_name['uint32_val']._loaded_options = None
  _globals['_TENSORPROTO'].fields_by_name['uint32_val']._serialized_options = b'\020\001'
  _globals['_TENSORPROTO'].fields_by_name['uint64_val']._loaded_options = None
  _globals['_TENSORPROTO'].fields_by_name['uint64_val']._serialized_options = b'\020\001'
  _globals['_TENSORPROTO']._serialized_start=73
  _globals['_TENSORPROTO']._serialized_end=553
  _globals['_VARIANTTENSORDATAPROTO']._serialized_start=555
  _globals['_VARIANTTENSORDATAPROTO']._serialized_end=647
# @@protoc_insertion_point(module_scope)
